# Generated by Django 5.2.15 on 2026-07-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_monitorrun_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrun',
            name='status',
            field=models.CharField(choices=[('running', 'En ejecución'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='running', max_length=10),
        ),
    ]
