# Generated by Django 5.2.15 on 2026-08-20 00:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_cleanup_history_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('baseline', 'Baseline'), ('new', 'Producto nuevo'), ('exit', 'Salida'), ('reentry', 'Reingreso'), ('price_drop', 'Reducción de precio')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_position', models.PositiveIntegerField(blank=True, null=True)),
                ('new_position', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DiscoveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notification_reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_entered_at', models.DateTimeField()),
                ('last_exited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('source', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutándose'), ('success', 'Exitosa'), ('incomplete', 'Incompleta'), ('failed', 'Fallida'), ('skipped', 'Omitida')], default='pending', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('pages_found', models.PositiveIntegerField(default=0)),
                ('products_found', models.PositiveIntegerField(default=0)),
                ('known_products', models.PositiveIntegerField(default=0)),
                ('new_products', models.PositiveIntegerField(default=0)),
                ('exits', models.PositiveIntegerField(default=0)),
                ('reentries', models.PositiveIntegerField(default=0)),
                ('price_drops', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('notifications_created', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DiscoveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='monitor.discoveryevent')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='discoveryevent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitor.discoveryproduct'),
        ),
        migrations.AddField(
            model_name='discoveryevent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitor.discoveryrun'),
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=2000)),
                ('source_type', models.CharField(choices=[('amazon_top_100', 'Amazon Top 100'), ('amazon_newest', 'Amazon Newest'), ('amazon_trackers', 'Amazon Trackers'), ('mercado_libre_seller', 'Mercado Libre Seller')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('price_drop_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('baseline_established', models.BooleanField(default=False)),
                ('baseline_established_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.discoveryrun')),
                ('last_successful_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.discoveryrun')),
            ],
            options={
                'verbose_name': 'Fuente de descubrimiento',
                'verbose_name_plural': 'Fuentes de descubrimiento',
                'ordering': ('source_type', 'name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='discoveryrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='monitor.discoverysource'),
        ),
        migrations.AddField(
            model_name='discoveryproduct',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='monitor.discoverysource'),
        ),
        migrations.AddConstraint(
            model_name='discoveryevent',
            constraint=models.UniqueConstraint(fields=('run', 'product', 'event_type'), name='unique_discovery_event_per_run'),
        ),
        migrations.AddConstraint(
            model_name='discoveryrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('source',), name='unique_running_discovery_source'),
        ),
        migrations.AddIndex(
            model_name='discoveryproduct',
            index=models.Index(fields=['source', 'is_present'], name='discovery_present_idx'),
        ),
        migrations.AddConstraint(
            model_name='discoveryproduct',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_discovery_product_source'),
        ),
    ]
